In [1]:
import numpy as np

In [3]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[3]

np.int64(4)

In [7]:
arr[1:5] # slicing the array from index 1 to 4

array([2, 3, 4, 5])

In [8]:
arr[3:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [10]:
arr_slice=arr[3::2] # slicing the array from index 3 to the end with a step of 2
arr_slice

array([ 4,  6,  8, 10])

In [21]:
arr=np.arange(1,31).reshape(6,5) # reshape the array to 5 rows and 6 columns
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [12]:
arr[0]

array([1, 2, 3, 4, 5, 6])

In [13]:
arr[-1]

array([25, 26, 27, 28, 29, 30])

In [15]:
arr[0,0]

np.int64(1)

In [16]:
arr[4,5]

np.int64(30)

In [20]:
slice=arr[0:2,1:3] # slicing the array from index 0 to 1 for rows and index 1 to 2 for columns
slice

array([[2, 3],
       [8, 9]])

In [24]:
arr[3:6,3:5]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [25]:
arr[:,2] #for column 2

array([ 3,  8, 13, 18, 23, 28])

In [33]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [34]:
bool_index=arr%2==0 # create a boolean index for even numbers
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [35]:
arr=arr[bool_index] # use the boolean index to filter the array
arr

array([12, 14, 16, 18, 20])