In [2]:
import numpy as np

In [3]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])

In [4]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [5]:
a1//a2

array([0, 0, 0, 0, 0])

In [6]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [7]:
l=[10,20,30,40,50]
arr=np.array(l)

In [8]:
arr+10

array([20, 30, 40, 50, 60])

In [10]:
arr2=np.arange(1,21).reshape(4,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [16]:
arr2=arr2+10
arr2

array([[31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [17]:
arr2*2

array([[ 62,  64,  66,  68,  70],
       [ 72,  74,  76,  78,  80],
       [ 82,  84,  86,  88,  90],
       [ 92,  94,  96,  98, 100]])

In [18]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [20]:
slice=a[:5]
slice=slice*10
slice

array([10, 20, 30, 40, 50])

In [21]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
# the above is example of  deep copy 
#the slice store in other memory location

In [23]:
a
b=a

In [25]:
b[0]=99

In [26]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [27]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
#the above is example of shallow copy


In [29]:
# if we used b=a.copy() then it will create a deep copy of a

In [32]:
mat1=np.array([[1,2],[3,4]])
mat2=np.array([[5,6],[7,8]])

In [33]:
mat1

array([[1, 2],
       [3, 4]])

In [34]:
mat2

array([[5, 6],
       [7, 8]])

In [37]:
mat1@mat2 #matrix multiplication

array([[19, 22],
       [43, 50]])

In [ ]:
np.dot(mat1,mat2) #matrix multiplication using dot function

array([[19, 22],
       [43, 50]])

In [40]:
mat1.T

array([[1, 3],
       [2, 4]])

In [41]:
#matrix can not be stacked

In [42]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])

In [43]:
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [44]:
np.hstack((a,b)) #horizontal stack

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
np.column_stack((a,b)) #column stack is used to stack 1D arrays as columns into a 2D array. It takes each input array and stacks them column-wise, resulting in a 2D array where each input array becomes a column.

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [47]:
c=np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [48]:
np.hsplit(c,2) #horizontal split

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [49]:
np.vsplit(c,2) #vertical split

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [51]:
for i in c:
    print(i) 

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
