In [1]:
print("hello")

hello


In [3]:
import numpy as np

In [5]:
arr=np.array([1,2,3])
print(arr)

[1 2 3]


In [6]:
a=[1,2,3,1.5,"hello"]
a

[1, 2, 3, 1.5, 'hello']

In [7]:
np.array(a)

array(['1', '2', '3', '1.5', 'hello'], dtype='<U32')

In [8]:
#vector is a 1D array
l=[[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
# now we have a 2D array which is also called a matrix

In [12]:
arr=np.arange(1,10,2)
arr

array([1, 3, 5, 7, 9])

In [ ]:
arr=np.zeros((3,3)) # 3 rows and 3 columns
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
arr=np.ones((2,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
arr=np.linspace(0, 10, 5) # 5 numbers between 0 and 10
arr
# spaces will be linearly spaced between 0 and 10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [30]:
arr=np.random.rand(3) # 3 rows and 3 columns of random numbers between 0 and 1
#normal distribution
#the numbers will be between 0 and 1
arr2=np.random.randn(10) # 10 random numbers from normal distribution
#the numbers will be between -3 and 3
print(arr)
print(arr2)

[0.67226215 0.7894267  0.25591949]
[ 1.0970204  -0.01255254 -1.14444786  0.74775042  1.37619591  0.96921728
  1.00899074 -0.12357355  0.54281763 -0.78498674]


In [31]:
np.random.randint(1,10,5) # 5 random integers between 1 and 10

array([7, 4, 9, 2, 9], dtype=int32)

In [ ]:
arr=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
arr[0] # first row


array([1, 2, 3])

In [35]:
arr.shape # shape of the array

(3, 3)

In [36]:
arr.size # number of elements in the array

9

In [37]:
arr.dtype # data type of the array

dtype('int64')

In [38]:
arr.min()

np.int64(1)

In [39]:
arr.max()

np.int64(9)

In [40]:
arr.sum()

np.int64(45)

In [41]:
np.sum(arr,axis=0) # sum of each column

array([12, 15, 18])

In [42]:
np.sum(arr,axis=1) # sum of each row

array([ 6, 15, 24])

In [44]:
arr.mean()

np.float64(5.0)

In [45]:
arr.std() # standard deviation of the array

np.float64(2.581988897471611)

In [51]:
arr.argmax() # index of the maximum element in the array

np.int64(8)

In [52]:
arr.argsort() # indices of the sorted array

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [56]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [57]:
arr.reshape(5,6) # reshape the array to 5 rows and 6 columns

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])