In [92]:
import numpy as np

In [93]:
# Valid Sudoku

In [94]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])


In [95]:
int(s.sum())

405

In [96]:
s.sum()

np.int64(405)

In [97]:
# row axis==1 and col axis==0 for sum function

In [98]:
b=np.sum(s,axis=1)
b==45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [99]:
for i in b:
    if i!=45:
        print("sudoku is not valid")
        break
else:
    print("for row it is valid")

for row it is valid


In [100]:
c=np.sum(s,axis=0)
c

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [101]:
c==45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [102]:
for i in c:
    if i!=45:
        print("sudoku is not valid")
        break
else:
    print("for col it is valid")

for col it is valid


In [103]:
s[0:3,:3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [104]:
s[0:3,3:6]

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [105]:
s[0:3,6:9]

array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

In [106]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n=s[i:i+3,j:j+3]  
        print(n.sum())

45
45
45
45
45
45
45
45
45


In [107]:
import numpy as np

In [108]:
# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])


In [109]:
data.shape

(5, 3)

In [110]:
data[:,0].mean()

np.float64(18.4)

In [111]:
data[:,1]

array([85, 92, 76, 65, 90])

In [112]:
np.max(data[:,2])

np.int64(95)

In [113]:
data[data[:,1]>90]

array([[19, 92, 88]])

In [114]:
data[:,1]+=5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [115]:
len(data[data[:,0]<19])

3

In [116]:
np.mean(data[:,1:2])

np.float64(86.6)

In [117]:
np.mean(data[:,2:3])


np.float64(83.2)

In [118]:
np.mean(data[:,1:],axis=0)

array([86.6, 83.2])

In [119]:
data[(data[:,1]>=80) & (data[:,2]>=80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [120]:
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [121]:
data[:,2][data[:,2]<75]=0
data


array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])